--- 
eureka: 
  client: 
    serviceUrl: 
      defaultZone: "http://localhost:8761/eureka"
      
  instance: 
    healthCheckUrlPath: "/healthCatalogo"
    metadataMap: 
      appOwner: AbelardoRDZ
      description: Aplicacion_ventas
    statusPageUrlPath: "/infoCatalogo"
    
server: 
  port: 1111
  
spring: 
  application: 
    name: servicio.catalogo

spring.datasource:
  url: "jdbc:mysql://localhost:3306/bdalmacen?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
  username: "root"
  password: "root"
  
spring.jpa:
 show-sql: true
 hibernate.ddl-auto: update
 database-platform: org.hibernate.dialect.MySQL5InnoDBDialect  
