#Spring configuration
spring:
   application:
      name: servicio.cesta
 #http server
server: 
   port: 1112
  #Discovery server acces
eureka:
    client:
      serviceUrl:
         defaultZone: http://172.17.0.4:8761/eureka
#configuracion de ribon para balanceo de carga entre los microservcios invocados
servicio.catalogo:
   ribbon:
      EnableZoneAffinity: true
      EnableZoneExclusive: false
      zoneAffinity:
         minAvailableServers: 1
         maxLoadPerServer: 0.8
         maxBlackOutServersPercentage: 0.6
security: 
  oauth2: 
    resource:
      user-info-uri: http://172.17.0.3:7777/user
